Resources:
  RekogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.RekogTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

  
