Resources:
  RekognitionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.rekognitionBucketName}
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - "*"
            AllowedMethods:
              - PUT
              - GET
            AllowedHeaders:
              - "*"